'use strict';

const yaml = require('js-yaml');

async function generateNotebook(context, recipeYaml, verification) {
  const recipe = yaml.load(recipeYaml);
  const meta = recipe.metadata || {};
  const agents = recipe.agents || [];
  const now = new Date().toISOString();

  return `# Verifiable Agent Notebook: ${meta.name || context.repoName}

> **Generated:** ${now}
> **Model:** ${meta.model || 'claude-sonnet-4-6'}
> **Verification:** ${verification.passed ? '✅ PASSED' : '❌ FAILED'}
> **Sandbox mode:** ${recipe.safety?.sandbox_mode ? 'ON' : 'OFF'}

---

## Table of Contents

1. [Repository Analysis](#1-repository-analysis)
2. [Multi-Agent Recipe Overview](#2-multi-agent-recipe-overview)
3. [Agent Roster](#3-agent-roster)
4. [Workflow Trace](#4-workflow-trace)
5. [Verification Report](#5-verification-report)
6. [Computer Use Session](#6-computer-use-session)
7. [Run It Yourself](#7-run-it-yourself)

---

## 1. Repository Analysis

**Repository:** \`${context.repoName}\`
**Files analyzed:** ${context.files?.length || 0}

### Stack Detected
${formatStack(context.stack)}

### Summary
\`\`\`
${context.summary || 'No summary available'}
\`\`\`

---

## 2. Multi-Agent Recipe Overview

\`\`\`yaml
${recipeYaml}
\`\`\`

---

## 3. Agent Roster

${agents.map(agent => formatAgent(agent)).join('\n\n')}

---

## 4. Workflow Trace

| Step | Agent | Action | Requires Approval |
|------|-------|--------|-------------------|
${(recipe.workflow || []).map(s =>
  `| ${s.step} | \`${s.agent}\` | ${s.action} | ${s.requires_approval ? '✋ Yes' : 'No'} |`
).join('\n')}

---

## 5. Verification Report

**Overall:** ${verification.passed ? '✅ PASSED' : '❌ FAILED'}

${verification.results.map(r => formatCheckResult(r)).join('\n\n')}

### Raw Report

\`\`\`yaml
${verification.report}
\`\`\`

---

## 6. Computer Use Session

The \`computer_use_agent\` can perform browser/UI tasks with full screenshot provenance.

### Example: Run a UI verification task

\`\`\`bash
# Start a Computer Use session (sandbox mode)
ANTHROPIC_API_KEY=your_key npx create-verifiable-agent \\
  https://github.com/your/repo \\
  --sandbox
\`\`\`

### Provenance chain
Every screenshot, click, and keystroke is logged with:
- Timestamp
- Agent ID
- Input hash
- Output hash
- Human review gate status

---

## 7. Run It Yourself

### Prerequisites
\`\`\`bash
node >= 18
npm >= 9
export ANTHROPIC_API_KEY=sk-ant-...
\`\`\`

### Install & run
\`\`\`bash
# Run on any GitHub repo
npx create-verifiable-agent https://github.com/org/repo

# Run the Mythos demo (no API key needed with --sandbox)
npx create-verifiable-agent --demo mythos --sandbox

# Auto-accept all edits (Pro plan plan mode)
npx create-verifiable-agent https://github.com/org/repo --accept-edits

# Full options
npx create-verifiable-agent --help
\`\`\`

### Output files
| File | Description |
|------|-------------|
| \`recipe.yaml\` | Multi-agent YAML recipe |
| \`verification-report.yaml\` | Self-consistency + provenance report |
| \`notebook.md\` | This notebook |
| \`collab-card.md\` | Human-AI collaboration card |

---

*Generated by [create-verifiable-agent](https://github.com/kju4q/verifiable-agent-recipe)*
`;
}

function formatStack(stack) {
  if (!stack) return '_No stack detected_';
  const lines = [];
  if (stack.languages?.length) lines.push(`- **Languages:** ${stack.languages.join(', ')}`);
  if (stack.frameworks?.length) lines.push(`- **Frameworks:** ${stack.frameworks.join(', ')}`);
  if (stack.infra?.length) lines.push(`- **Infrastructure:** ${stack.infra.join(', ')}`);
  return lines.length ? lines.join('\n') : '_Stack details unavailable_';
}

function formatAgent(agent) {
  return `### Agent: \`${agent.id}\` — ${agent.role}

| Field | Value |
|-------|-------|
| Model | \`${agent.model}\` |
| Computer Use | ${agent.computer_use ? '✅ Yes' : 'No'} |
| Tools | ${(agent.tools || []).map(t => `\`${t}\``).join(', ') || 'none'} |

**Responsibilities:**
${(agent.responsibilities || []).map(r => `- ${r}`).join('\n')}

**Inputs:** ${(agent.inputs || []).join(', ')}
**Outputs:** ${(agent.outputs || []).join(', ')}`;
}

function formatCheckResult(r) {
  const icon = r.passed ? '✅' : '❌';
  return `### ${icon} ${r.name.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())}

${r.details || ''}
${r.score !== undefined ? `\n**Confidence score:** ${(r.score * 100).toFixed(0)}%` : ''}`;
}

module.exports = { generateNotebook };
